### PR TITLE
Create News API.py

### PR DESCRIPTION
**Pull request by SachinDabhade**

### CODE REVIEW

**Comment by mrkc2303** [comment]
Thanks!
Kindly change the file name to PascalCase and add the project to respective readme

**Comment by SachinDabhade** [comment]
I have changed it, can you please review it

**Comment by mrkc2303** [comment]
No changes are visible!
Kindly Check!

**Comment by SachinDabhade** [comment]
Done it

**Comment by SachinDabhade** [comment]
oo, yeah, but now I have made changes, please review it

**Pull request closed without merging**
