### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by madhuashish**
Adding link to the README.md file

### CODE REVIEW

**Comment by yellowberard** [comment]
Please add the link  in readme file in branch patch-2 so all the change is reflected in PR #10 so that we can merge the PR. you are creating 2 PR for same question which we cannot accept. @madhuashish

**Comment by madhuashish** [comment]
Can you tell me how to do that?Like can I attact the readme file in PR#10?

**Comment by madhuashish** [comment]
Or can you do that from your side to merge the PRs #10 and #16 into one PR

**Comment by yellowberard** [comment]
You have make changes in readme file and push that changes in branch patch-2 then the changes in PR 10 will reflect if not then close both the PR and create a new PR with the changes

**Pull request closed without merging**
